server:
  port: 9011

spring:
  application:
    name: discovery-server
  freemarker:
    prefer-file-system-access: false
    template-loader-path:
      - classpath:/templates/

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9010/eureka/,http://localhost:9011/eureka/
