server:
  port: 9020

spring:
  application:
    name: auth

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9010/eureka/,http://127.0.0.1:9011/eureka/