-- MySQL Script generated by MySQL Workbench
-- Tue Jun 16 17:51:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `market` DEFAULT CHARACTER SET utf8mb4 ;
USE `market` ;

-- -----------------------------------------------------
-- Table `market`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '角色名称',
  `service_type` VARCHAR(45) NULL COMMENT '服务类型：platform 平台, merchant 商户, consumer 消费者',
  `status` INT NULL,
  `update_time` DATETIME NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色';


-- -----------------------------------------------------
-- Table `market`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NULL COMMENT '昵称',
  `head_img` VARCHAR(512) NULL COMMENT '头像',
  `username` VARCHAR(45) NULL COMMENT '用户名',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `password` VARCHAR(45) NULL COMMENT '密码',
  `status` INT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`resource` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT(20) NULL,
  `name` VARCHAR(45) NULL COMMENT '资源名称',
  `type` INT NULL COMMENT '资源类型 1 请求地址 2 web菜单',
  `path_id` INT NULL COMMENT '地址id',
  `path` VARCHAR(512) NULL COMMENT '地址',
  `level` INT NULL COMMENT '级别',
  `status` INT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `path_index` (`path_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`user_role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) NULL,
  `user_id` BIGINT(20) NULL,
  `status` INT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`role_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`role_resource` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) NULL,
  `resource_id` BIGINT(20) NULL,
  `status` INT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`user_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`user_token` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NULL,
  `client` VARCHAR(45) NULL COMMENT '客户端类型：IOS，ANDROID，WEB',
  `token` VARCHAR(128) NULL COMMENT '登录凭证',
  `token_expire` BIGINT(20) NULL COMMENT '过期时间',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
