server:
  port: 9020

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost/market?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456@yyM
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9010/eureka/,http://127.0.0.1:9011/eureka/